name: Create pop_pop release

on:
  push:
    tags:
      - pop_pop-v[0-9]+.[0-9]+.[0-9]*

defaults:
  run:
    working-directory: packages/pop_pop

env:
  FLUTTER_VERSION: 3.41.1

jobs:
  analyze_test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --coverage

  publish_release:
    name: Publish to pub.dev
    runs-on: ubuntu-latest
    needs: analyze_test
    environment: pub.dev
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.FLUTTER_VERSION }}
      - run: flutter pub get
      - name: Publish - dry run
        run: dart pub publish --dry-run
      - name: Publish to pub.dev
        run: dart pub publish -f

  create_github_release:
    name: Create GitHub Release
    needs: publish_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
