name: Create pop_pop release

on:
  push:
    tags:
      - pop_pop-v[0-9]+.[0-9]+.[0-9]*

defaults:
  run:
    working-directory: packages/pop_pop

jobs:
  analyze_test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.1'
          channel: stable

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test --coverage

  publish_release:
    name: Publish to pub.dev
    needs: analyze_test
    permissions:
      id-token: write

    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: pub.dev
      working-directory: packages/pop_pop

  create_github_release:
    name: Create GitHub Release
    needs: publish_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
